# Generated by Django 5.1.1 on 2024-10-09 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvcrud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Car',
        ),
    ]
